### ISSUE TITLE
User Story: As a player, I want to have the option to view a list of all words in the game, so that I can see which words are available.

### ISSUE THREAD

**Issue by newworldhost** [newworldhost/hackathon#14]
**Acceptance criteria**
- [x] A "View Words" button is present on the game interface.

- [x] Clicking the "View Words" button displays a list of all words currently in the game.

- [x] The list is scrollable if it contains more words than can fit on the screen.

**Tasks:**

- [x] Implement a button labeled "View Words" on the game interface.

- [x] Create a function to retrieve and display the list of words.

- [x] Ensure the list is scrollable if it exceeds screen height.

- [x] Test the functionality to ensure all words are displayed correctly.
