### ISSUE TITLE
As a user, I want to add tasks to my to-do list so that I can keep track of what I need to do.

### ISSUE THREAD

**Issue by newworldhost** [newworldhost/hackathon#7]
**Acceptance Criteria**

- [x]  I can type the task details into an input field.

- [x]  I can click an "Add Task" button to add the task to the list.

- [x] The new task appears in the task list immediately after adding.

 **Tasks** 

- [x] Create an input field for users to type in their task details.

 

- [x] Add an "Add Task" button next to the input field.

 **Write JavaScript code to:**

- [x] Capture the input value when the button is clicked.

- [x] Add the task to a task list array.

- [x] Dynamically update the DOM to display the new task in the list.
